[project]
name = "ptags-nvim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Daniel Kuettel", email = "dkuettel@gmail.com" }]
requires-python = ">=3.13"
dependencies = ["tabulate>=0.9.0", "tree_sitter>=0.20.1", "typer>=0.7.0"]

[project.scripts]
ptags-nvim = "ptags_nvim:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
